name: Build and Publish Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true

    - name: Build and Publish Image
      run: mvn --batch-mode -DskipTests package
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
